### ISSUE TITLE
error response for put request /users/update

### ISSUE THREAD

**Issue by AdithyaVarma123** [t348575/elective-managment-system-api#13]
put request for users/update returns the following error response:
`{status: true, failed: Array(1)}
failed: Array(1)
0:
batch: "2018-4-BTECH-CSE"
name: "Karthik Prakash Desai"
password: "$argon2i$v=19$m=4096,t=3,p=1$9M6J1CWi+3am+c1RSKIecQ$REsiWITzbJx0rY3iwgHAToi82gJ1RcV/nJGkZgslp5w"
rollNo: "CB.EN.U4CSE18125"
__proto__: Object
length: 1
__proto__: Array(0)
status: true
__proto__: Object`

**Comment by t348575** [comment]
Non-reproducible
