### ISSUE TITLE
 ​/electives​/add endpoint fails

### ISSUE THREAD

**Issue by AdithyaVarma123** [t348575/elective-managment-system-api#5]
`const body = {
      "name": this.eName,
      "description": this.desc,
      "courseCode": this.courseCode,
      "version": this.version,
      "strength": this.strength,
      "attributes": [
        {
          "value": "asd",
          "key": "dsa"
        }
      ],
      "batches": this.batches,
      "teachers": [
        this.teachers
      ]
    };`

this results in 

`{status: true, failed: Array(1)}
failed: Array(1)
0:
attributes: [{…}]
batches: ["2018-4-BTECH-CSE"]
courseCode: "15cse211"
description: "asd"
name: "pattern"
strength: 32
teachers: ["CB.EN.U4CSE18125"]
version: 1
__proto__: Object
length: 1
__proto__: Array(0)
status: true
__proto__: Object`

status code :200

**Comment by t348575** [comment]
Refer #6
